### ISSUE TITLE
获取验证码的时候貌似有问题

### ISSUE THREAD

**Issue by fierywing** [LQBing/docker-cqhttp-mirai#1]
看的到验证码但是输入无任何反应 CTRL-C后tmp文件夹也没有图片

**Comment by LQBing** [comment]
请问你是根据readme.md中使用说明，使用`docker run --rm -it --name cqhttp-mirai --env-file .env -v $(pwd)/tmp:/tmp lqbing/cqhttp-mirai`来运行的吗？
另外，如果要访问`tmp`目录（当前目录下的tmp目录）中的图片文件，你要做的是保持docker run运行不ctrl-c的同时通过winscp或者xshell一类的远程传输工具把图片拉出来打开的（因为无GUI的linux是无法直接打开图片的）。而不是ctrl-c，因为这样主进程会被杀掉，再次运行会重新连接生成新的验证码。

**Comment by fierywing** [comment]
是的 输入这个命令后会开始运行然后输出验证码, 提示输入验证码后 接下来输入任何命令都没有反馈 不管是 回车尝试直接重置验证码还是 输入验证码

**Comment by LQBing** [comment]
> 是的 输入这个命令后会开始运行然后输出验证码, 提示输入验证码后 接下来输入任何命令都没有反馈 不管是 回车尝试直接重置验证码还是 输入验证码

是我的问题，用管道输入config.txt会导致忽略输入的问题。image和readme.md都更新了，重新`docker pull lqbing/cqhttp-mirai`就可以了。

新的首次运行输入验证码用下面的命令，然后输入`login 123456789 password` （替换自己的用户名密码）

```shell
docker run --rm -it --name cqhttp-mirai --env-file .env -v $(pwd)/tmp:/tmp  --entrypoint="/bin/bash" lqbing/cqhttp-mirai run.sh
```

另外，cqhttp-mirai虽然更新了0.2.2但是好像暂时还不稳定，过两天我再更新image
