### ISSUE TITLE
请问大佬，支持arm64架构嘛

### ISSUE THREAD

**Issue by lstkpeter** [LQBing/docker-cqhttp-mirai#2]
使用arm64执行docker run时出现
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by LQBing** [comment]
我这里只是把cqhttp-mirai的jar包封装进了docker image，arm的问题你可能要去https://github.com/yyuueexxiinngg/cqhttp-mirai/issues 找cqhttp-mirai的作者去问了。（我在那边没有看到arm的release）

**Comment by lstkpeter** [comment]
谢谢大佬~
我换成amd64架构的服务器后，遇到了登陆的问题。验证码可以看到，我也能看到图片，但是在命令行输出后回车，卡死没有反应，也没有登陆成功，请问是有什么问题嘛

**Comment by LQBing** [comment]
> 谢谢大佬~
> 我换成amd64架构的服务器后，遇到了登陆的问题。验证码可以看到，我也能看到图片，但是在命令行输出后回车，卡死没有反应，也没有登陆成功，请问是有什么问题嘛

readme.md的使用说明有写。

直接`docker-compose up -d`是不能输入信息的，要先`docker run -it `过了验证（device.json文件一样的话腾讯不会再次发验证码）再`docker-compose up -d`启动

```shell
docker run --rm -it --name cqhttp-mirai --env-file .env -v $(pwd)/tmp:/tmp lqbing/cqhttp-mirai
```

**Comment by lstkpeter** [comment]
> > 谢谢大佬~
> > 我换成amd64架构的服务器后，遇到了登陆的问题。验证码可以看到，我也能看到图片，但是在命令行输出后回车，卡死没有反应，也没有登陆成功，请问是有什么问题嘛
> 
> readme.md的使用说明有写。
> 
> 直接`docker-compose up -d`是不能输入信息的，要先`docker run -it `过了验证（device.json文件一样的话腾讯不会再次发验证码）再`docker-compose up -d`启动
> 
> ```shell
> docker run --rm -it --name cqhttp-mirai --env-file .env -v $(pwd)/tmp:/tmp lqbing/cqhttp-mirai
> ```

是的大佬，我就是按照这个步骤来的，验证码在命令行显示了，在tmp文件夹下也有，但是输入在命令行中确实无反应

**Comment by LQBing** [comment]
稍等，我去试试

**Comment by LQBing** [comment]
是我的问题，用管道输入config.txt会导致忽略输入的问题。image和readme.md都更新了，重新`docker pull lqbing/cqhttp-mirai`就可以了。

新的首次运行输入验证码用下面的命令，然后输入`login 123456789 password` （替换自己的用户名密码）

```shell
docker run --rm -it --name cqhttp-mirai --env-file .env -v $(pwd)/tmp:/tmp  --entrypoint="/bin/bash" lqbing/cqhttp-mirai run.sh
```

另外，cqhttp-mirai虽然更新了0.2.2但是好像暂时还不稳定，过两天我再更新image

**Comment by LQBing** [comment]
另外，截图最好把敏感信息打码，我在上面找到了你的QQ和服务器IP

**Comment by lstkpeter** [comment]
> 另外，截图最好把敏感信息打码，我在上面找到了你的QQ和服务器IP

好哒，谢谢大佬~ 麻烦啦！
